# Generated by Django 4.0.4 on 2022-08-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='image',
            field=models.ImageField(height_field=300, null=True, upload_to='files/images', width_field=300),
        ),
    ]
